# Generated by ChatGPT
# Compiles to a static library called libprocessor.a

CC = gcc
CFLAGS = -Wall -Wextra -O2 -Iinclude

SRC = $(wildcard debugger/*.c) ememory.c processor.c
OBJ = $(SRC:.c=.o)

LIB = libprocessor.a

all: $(LIB)

$(LIB): $(OBJ)
	@ar rcs $@ $^
	@rm -f $(OBJ)    # automatically remove .o files after building the library


clean:
	rm -f $(OBJ) $(LIB)
